import abc
import dataclasses
import uuid


@dataclasses.dataclass
class HamiltonResponse(abc.ABC):
    pass


@dataclasses.dataclass
class CommandExecutingResponse(HamiltonResponse):
    pass


@dataclasses.dataclass
class HamiltonCommand:
    """
    Base class for all Hamilton commands.
    The communication contract is that a serialized command will contain the following fields:
    - id: a unique identifier for the command, generated by the sender
    - command: the name of the command, which should match the class name of the command
    - args: a dictionary of arguments specific to the command, which should be defined by the subclass
    """

    id: uuid.UUID = dataclasses.field(init=False, default_factory=uuid.uuid4)

    @abc.abstractmethod
    def as_dict(self) -> dict:
        return {"id": str(self.id), "command": self.__class__.__name__, "args": {}}

    @abc.abstractmethod
    def parse_response(self, data: dict) -> HamiltonResponse:
        pass
